### ISSUE TITLE
Investigate usage of official heroku-php-buildpack

### ISSUE THREAD

**Issue by josegonzalez** [FriendsOfCake/app-template#50]
I got it working by setting the following in a `Procfile`:

```
web: vendor/bin/heroku-php-apache2 webroot
```

Nginx didn't work, though there is no reason it shouldn't. Haven't had time to investigate thoroughly, so filing an issue to make sure this doesn't get lost.

**Comment by chrisvogt** [comment]
I'm submitting a PR for this right now. The CHH buildpack does not seem to be working for CakePHP anymore and [is abandoned at the moment](https://github.com/CHH/heroku-buildpack-php/issues/167).

The changes in 74ce0ec get this app template working again, and I've updated the README documentation for the [official buildpack](https://github.com/heroku/heroku-buildpack-php) and added instructions on setting the necessary DATABASE_URL config variable.

**Comment by HarderWork** [comment]
Redis isn't part of the buildpack. Solved by adding it to the `require`-section of `composer.json`:
`"ext-redis" : "*"`
File-engine is used by default in app-template, but makes no sense on an isolated heroku dyno, so maybe it should be mentioned in the heroku-section of the readme?
